export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as RegisterPage } from './register/RegisterPage'
export { default as LoginPage } from './login/LoginPage'